# Generated by Django 6.0.2 on 2026-02-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('REGISTER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory_test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=40)),
                ('test_price', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.FloatField(default=0)),
                ('lab_tests', models.FloatField(default=0)),
                ('medication', models.FloatField(default=0)),
                ('room', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REGISTER.register_master')),
            ],
        ),
    ]
