# Generated by Django 6.0.2 on 2026-02-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('REGISTER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminprofile_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Image/')),
                ('Document', models.FileField(upload_to='Document/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REGISTER.register_master')),
            ],
        ),
    ]
