# Generated by Django 6.0.2 on 2026-02-17 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Master',
            fields=[
                ('Reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Mobile', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=40)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Role_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
