# Generated by Django 6.0.2 on 2026-02-17 05:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('REGISTER', '0001_initial'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doct_name', models.CharField(max_length=60)),
                ('doct_contact', models.CharField(max_length=15)),
                ('p_name', models.CharField(max_length=100)),
                ('p_mobile', models.CharField(max_length=15)),
                ('p_address', models.TextField()),
                ('p_gender', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('p_disease', models.CharField(max_length=255)),
                ('todaydate', models.DateField(auto_now=True)),
                ('a_date', models.DateField(default=datetime.date.today)),
                ('fromtime', models.TimeField(default=datetime.time(9, 0))),
                ('totime', models.TimeField(default=datetime.time(17, 0))),
                ('status', models.CharField(default='pending', max_length=30)),
                ('doct_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REGISTER.register_master')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTestReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REGISTER.register_master')),
                ('tests', models.ManyToManyField(to='Staff.laboratory_test')),
            ],
        ),
    ]
